### ISSUE TITLE
OpenAPI tool

### ISSUE THREAD

**Issue by Tomas2D** [i-am-bee/bee-agent-framework#105]
Take the following implementation and add it to the framework.

https://github.com/i-am-bee/bee-api/blob/main/src/runs/execution/tools/api-call-tool.ts#L42C1-L43C1

Are there any blockers or things to consider? @pilartomas, @xjacka

**Comment by xjacka** [comment]
1. The tool should accept the `apiKey` parameter.
2. The tool should accept the `http_proxy_url` parameter and use this proxy for all requests.

**Comment by Tomas2D** [comment]
The second should be optional. I would allow the user to pass custom overrides for underlying `fetch` parameter calls.

**Comment by planetf1** [comment]
I'd be interested to take a look as a first issue within the framework/api.

Previously I've been looking at the stack and raising a few issues/PRs 

I think the request here is to add the API tool into the built in tools (as documented [here](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/tools.md)), similar to how we have google, wikipedia, openMeteo etc. 

I'm not certain on what then needs to be added/left in the bee-api itself since in general custom tools are found dynamically. For core tools, mostly it just seems to require creating an instance of the tool

**Comment by xjacka** [comment]
Yes, this issue is about migrating [this](https://github.com/i-am-bee/bee-api/blob/main/src/runs/execution/tools/api-call-tool.ts) basic implementation to the framework and making it more robust. After that, we will use this tool instead of the current implementation in the API. This issue is only about the framework part.

**Comment by mmurad2** [comment]
@planetf1 I just assigned you the ticket, feel free to reach out if you have any questions/blockers!

**Comment by planetf1** [comment]
@mmurad2 thanks

I'm making a first-pass at the change. I have implementation code, and just debugging a simple e2e test.
Will share as a draft PR once a basic test works

**Comment by planetf1** [comment]
I've added a first-pass draft PR. There is still more to do, but since I am just learning about the bee framework, it would be great if you could check the nature of the change I'm proposing matches your expectations.

I made a few changes from the original code
 - http proxy is now a parameter
 - I removed the encryption of the api key (we don't have it in meteo, and it would require configuration + the crypto implementation from the framework)
 
Tests need more work
 - what endpoint could we test against? 
   - do we need to spin up a simple server for our e2e test ?
   - or is there a public endpoint it's ok to use
   - similar for proxy
 - only a simple 'happy path' is coded to check *something* is sent and received. The response isn't valid, and may not be correct.
  - many more parm combinations need testing
  
 There's also improvements to the tool itself - such as how error responses are handled, timeout configuration etc.

**Comment by Tomas2D** [comment]
@planetf1 I provided you with feedback a few weeks ago. Are you will to work on this?

**Comment by planetf1** [comment]
Hi @Tomas2D thanks for the feedback. I'm not going to be able to spend time on this in the short term, so please do reassign if needed.
