### ISSUE TITLE
OpenMeteo tool optimization

### ISSUE THREAD

**Issue by michael-desmond** [i-am-bee/bee-agent-framework#110]
**Is your feature request related to a problem? Please describe.**
Using openMeteo with Granite 3.0 8b and I ran into a few issues that may be worth us looking into. Also touches on the general topic of tool optimization.

1. The tool name `openMeteo` is not language intuitive i.e. its not obviously descriptive of its function. As such the LLM will sometimes use the tool to perform actions its not intended for. 
2. The tool responds with metadata that is probably not useful to the calling agent. 
https://github.com/i-am-bee/bee-agent-framework/blob/9e107d75f570032528f1b46dec231f8d23db8741/src/tools/weather/openMeteo.ts#L45C1-L52C21
3. Inclusion of both daily and hourly weather data seems unnecessary. A model with a 4k context window has its token memory consumed by a single response in some forecasting circumstances. 
4. The selection of current, daily and hourly data are somewhat arbitrary and the naming is not ideal

**Describe the solution you'd like**
1. Rename the tool to something intuitive such as GetWeatherForecast of WeatherForecast to make obvious its function. This should marginally help any LLM to more consistently utilize the tool.
2. Minimize the tool response, removing  latitude, longitude, generationtime_ms, utc_offset_seconds, timezone, timezone_abbreviation and elevation.
3. Add a configuration option to limit response to daily, hourly or both. This way smaller models could be configured to save token memory.
4. Do a pass over the variables selected for the various forecast ranges i.e. 
hourly-> Apparent Temperature, Relative Humidity (2 m), Precipitation Probability (temperature, humidity, precipitation)
daily -> Maximum Apparent Temperature (2 m), Minimum Apparent Temperature (2 m), Precipitation Probability Max
current -> Apparent Temperature, Relative Humidity (2 m), Precipitation

**Comment by Tomas2D** [comment]
1. That is a matter of subject because `OpenMeteo` is a well-known service. Renaming is a challenging task because, in the future, you can have multiple weather forecast providers in the framework. How would you differentiate between them?
2. Yes, we can probably remove those extra metadata. Feel free to do a PR. I am just worried about the timezone, as well.
3. How would you do that?
4. 👍🏻 

What do you think @matoushavlena ?

**Comment by geneknit** [comment]
@Tomas2D this is a broader issue around LLM capabilities and needing language that an LLM can traverse. LLMs shouldn't be expected to generate a plan to call OpenMeteo, they should be expected to plan to get_weather_forecast. 
@dakshiagrawal has proposed a layer of abstractions over common tools like search_internet that sits between branded tools and the LLM. This will (a) fix the problem descreibed by @michael-desmond and (b) enable greater flexibliity to add tools (e.g. if a developer pays for a subscription weather service). Off the bat I can think of this being very useful for users to bring their own RAG solutions to a Bee agent.

**Comment by michael-desmond** [comment]
@Tomas2D PR is here #155. This simplifies the output (to an extent) and allows us to configure the tool for use with a smaller context windowed model (by turning off hourly data). 

I also think that the input schema may not need the latitude and longitude option? is there a use case for this?

**Comment by Tomas2D** [comment]
@michael-desmond I think that `latitude` / `longitude` may be useful for some scenarios, but it might confuse the model.

**Comment by matoushavlena** [comment]
Yes, `latitude` / `longitude` is indeed useful for the location tool that is implemented on the UI layer (where we are using browser's `GeoLocation API`).

**Comment by matoushavlena** [comment]
1. I think it's better to call the tool in the fashion of what it does, rather what the underlying service is called. The underlying service could be switchable. I understand that each service has it's own unique API, but the tools should be abstract. And if two tools need to have different input schema, the names should reflect that. If someone requires a more specialized tool, they should implement it themselves.

Regarding daily vs hourly. I think precipitation is something you want hourly, but temperature could be done on a daily basis. Anyway, the goal is to limit what the tool does. In this case I would vote that it only returns precipitation and temperature.

**Comment by dakshiagrawal** [comment]
+1 to comment above by @matoushavlena . The tools for popular tools (searching internet, finding out weather, file search, etc.) need to be define abstractly in such a way that their input and outputs are LLM friendly. It is then the job of the tool developer to implement this LLM friendly input/output APIs using whatever underlying service they want. 

Bee team could implement one instance of these popular tools.

**Comment by dakshiagrawal** [comment]
For example, say an abstract tool definition calls for hourly fetching of precipitation by latitude/longitude. Suppose my underlying tool does not allow me to query by latitude/longitude, then tool response should be informative saying that please provide city, state, etc. so that the agent has a chance to use another tool to convert latitude/longitude to a city, state. Wrapping an existing API (e.g., OpenMeteo) and making it LLM friendly in this way is tool-builder's job. 

Another crisp example - suppose the tool does allow query by latitude/longitude. Given that LLMs have an issue with copy and pasting numbers and may further confuse between which number of latitude and which is longitude given a variety of formats in which these two numbers are specified (e.g., (41.40338, 2.17403) versus (41°24'12.2"N 2°10'26.5"E) versus (41 24.2028, 2 10.4418)), we might surmise that extracting latitude, longitude might be tough from previous messages. And even if LLM does manage to extract these numbers, reformatting them in as per abstract API might be impossible for LLMs to do. 

So we change abstract APIs to make a large number of formats so that LLMs does not need to reformat. We then check if Llama 70b can reasonably extract latitude and longitude - perhaps it does quite well. We check (through instrumentation) whether an 8b model can do it well too - perhaps not. We now end up in a situation, where based on the model, tool should modulate its behavior - for example, if an 8b model is being used, we supply it a definition of abstract tool where finding weather by latitude/longitude is suppressed...

These interactions between model and tools need to be relatively configurable/flexible and there is a role for a developer (tool developer/agent developer) who use these configurable knobs and create a combination that actually works.
